sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_success:
  - npminstall codecov && codecov --disable=gcov
